version: '3'

services:
  api:
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors --http httptools
      --log-config=log-conf.conf
      --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}"
    command:
      mongod --quiet --logpath /dev/null